sudo: required

language: ruby

services:
    - docker

before_install:
    - docker pull nogsantos/nodejs    
    - docker run -itd --name nodesantos nogsantos/nodejs
    - docker ps -a
    - docker rm -f /nodesantos